import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import ThemeProvider from './components/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body
        className={`${inter.className} min-h-screen bg-white text-black dark:bg-gray-900 dark:text-white`}
      >
        <ThemeProvider>
          <Navbar />
          <div className="pt-16">
            <div className="max-w-screen-xl mx-auto">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
